services:
  - type: web
    name: e2pg
    runtime: docker
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: e2pg
          property: connectionString
databases:
  - name: e2pg
    plan: free
