services:
  - type: web
    name: shovel
    runtime: docker
    autoDeploy: false
    envVars:
      - key: PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: shovel
          property: connectionString
databases:
  - name: shovel
    plan: standard
